CREATE TABLE PERSONAL_EXPENSES (
    EXPENSE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    EXPENSE_DATE DATE,
    CATEGORY VARCHAR2(30),
    DESCRIPTION VARCHAR2(100),
    AMOUNT NUMBER(10,2),
    PAYMENT_METHOD VARCHAR2(30)
);
